﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Selfdoctor_TrainingModels
{
    public partial class DiabetesDiagnosticML
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Pregnancies", @"Pregnancies"),new InputOutputColumnPair(@"Glucose", @"Glucose"),new InputOutputColumnPair(@"BloodPressure", @"BloodPressure"),new InputOutputColumnPair(@"SkinThickness", @"SkinThickness"),new InputOutputColumnPair(@"Insulin", @"Insulin"),new InputOutputColumnPair(@"BMI", @"BMI"),new InputOutputColumnPair(@"DiabetesPedigreeFunction", @"DiabetesPedigreeFunction"),new InputOutputColumnPair(@"Age", @"Age")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Pregnancies",@"Glucose",@"BloodPressure",@"SkinThickness",@"Insulin",@"BMI",@"DiabetesPedigreeFunction",@"Age"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"Outcome",inputColumnName:@"Outcome"))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy(new LbfgsMaximumEntropyMulticlassTrainer.Options(){L1Regularization=0.05985988F,L2Regularization=0.03125F,LabelColumnName=@"Outcome",FeatureColumnName=@"Features"}))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
}
