// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Selfdoctor_TrainingModels
{
    public partial class DiabetesDiagnosticML
    {
        /// <summary>
        /// model input class for DiabetesDiagnosticML.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Pregnancies")]
            public float Pregnancies { get; set; }

            [ColumnName(@"Glucose")]
            public float Glucose { get; set; }

            [ColumnName(@"BloodPressure")]
            public float BloodPressure { get; set; }

            [ColumnName(@"SkinThickness")]
            public float SkinThickness { get; set; }

            [ColumnName(@"Insulin")]
            public float Insulin { get; set; }

            [ColumnName(@"BMI")]
            public float BMI { get; set; }

            [ColumnName(@"DiabetesPedigreeFunction")]
            public float DiabetesPedigreeFunction { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"Outcome")]
            public float Outcome { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for DiabetesDiagnosticML.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Pregnancies")]
            public float Pregnancies { get; set; }

            [ColumnName(@"Glucose")]
            public float Glucose { get; set; }

            [ColumnName(@"BloodPressure")]
            public float BloodPressure { get; set; }

            [ColumnName(@"SkinThickness")]
            public float SkinThickness { get; set; }

            [ColumnName(@"Insulin")]
            public float Insulin { get; set; }

            [ColumnName(@"BMI")]
            public float BMI { get; set; }

            [ColumnName(@"DiabetesPedigreeFunction")]
            public float DiabetesPedigreeFunction { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"Outcome")]
            public uint Outcome { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("DiabetesDiagnosticML.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
