// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Selfdoctor_TrainingModels
{
    public partial class HepatitisDiagnosticML
    {
        /// <summary>
        /// model input class for HepatitisDiagnosticML.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"column1")]
            public float Column1 { get; set; }

            [ColumnName(@"Category")]
            public string Category { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"Sex")]
            public string Sex { get; set; }

            [ColumnName(@"ALB")]
            public float ALB { get; set; }

            [ColumnName(@"ALP")]
            public float ALP { get; set; }

            [ColumnName(@"ALT")]
            public string ALT { get; set; }

            [ColumnName(@"AST")]
            public float AST { get; set; }

            [ColumnName(@"BIL")]
            public float BIL { get; set; }

            [ColumnName(@"CHE")]
            public float CHE { get; set; }

            [ColumnName(@"CHOL")]
            public float CHOL { get; set; }

            [ColumnName(@"CREA")]
            public float CREA { get; set; }

            [ColumnName(@"GGT")]
            public float GGT { get; set; }

            [ColumnName(@"PROT")]
            public float PROT { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for HepatitisDiagnosticML.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"column1")]
            public float Column1 { get; set; }

            [ColumnName(@"Category")]
            public uint Category { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"Sex")]
            public float[] Sex { get; set; }

            [ColumnName(@"ALB")]
            public float ALB { get; set; }

            [ColumnName(@"ALP")]
            public float ALP { get; set; }

            [ColumnName(@"ALT")]
            public float[] ALT { get; set; }

            [ColumnName(@"AST")]
            public float AST { get; set; }

            [ColumnName(@"BIL")]
            public float BIL { get; set; }

            [ColumnName(@"CHE")]
            public float CHE { get; set; }

            [ColumnName(@"CHOL")]
            public float CHOL { get; set; }

            [ColumnName(@"CREA")]
            public float CREA { get; set; }

            [ColumnName(@"GGT")]
            public float GGT { get; set; }

            [ColumnName(@"PROT")]
            public float PROT { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("HepatitisDiagnosticML.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
